function get_bibtex() {
const bibtexData = {
'infocom16-wifi': `@inproceedings{pei2016wifi,
  title={WiFi can be the weakest link of round trip network latency in the wild},
  author={Pei, Changhua and Zhao, Youjian and Chen, Guo and Tang, Ruming and Meng, Yuan and Ma, Minghua and Ling, Ken and Pei, Dan},
  booktitle={Proceedings of the 35th Annual IEEE International Conference on Computer Communications},
  pages={1--9},
  year={2016},
  organization={IEEE}
}`,
'mobisys16-sui': `@inproceedings{sui2016characterizing,
  title={Characterizing and improving wifi latency in large-scale operational networks},
  author={Sui, Kaixin and Zhou, Mengyu and Liu, Dapeng and Ma, Minghua and Pei, Dan and Zhao, Youjian and Li, Zimu and Moscibroda, Thomas},
  booktitle={Proceedings of the 14th Annual International Conference on Mobile Systems, Applications, and Services},
  pages={347--360},
  year={2016}
}`,
'ubicomp16-EDUM': `@inproceedings{zhou2016edum,
  title={EDUM: classroom education measurements via large-scale WiFi networks},
  author={Zhou, Mengyu and Ma, Minghua and Zhang, Yangkun and SuiA, Kaixin and Pei, Dan and Moscibroda, Thomas},
  booktitle={Proceedings of the 2016 acm international joint conference on pervasive and ubiquitous computing},
  pages={316--327},
  year={2016}
}`,
'iwqos16-privacy': `@inproceedings{sui2016your,
  title={Your trajectory privacy can be breached even if you walk in groups},
  author={Sui, Kaixin and Zhao, Youjian and Liu, Dapeng and Ma, Minghua and Xu, Lei and Zimu, Li and Pei, Dan},
  booktitle={Proceedings of the IEEE/ACM 24th International Symposium on Quality of Service (IWQoS)},
  pages={1--6},
  year={2016},
  organization={IEEE}
}`,
'iwqos17-schedule': `@inproceedings{ma2017you,
  title={You can hide, but your periodic schedule can't},
  author={Ma, Minghua and Zhao, Kai and Sui, Kaixin and Xu, Lei and Li, Yong and Pei, Dan},
  booktitle={Proceedings of the IEEE/ACM 25th International Symposium on Quality of Service (IWQoS)},
  pages={1--6},
  year={2017},
  organization={IEEE}
}`,
'issre18-stepwise': `@inproceedings{ma2018robust,
  title={Robust and rapid adaption for concept drift in software system anomaly detection},
  author={Ma, Minghua and Zhang, Shenglin and Pei, Dan and Huang, Xin and Dai, Hongwei},
  booktitle={Proceedings of the IEEE 29th International Symposium on Software Reliability Engineering (ISSRE)},
  pages={13--24},
  year={2018},
  organization={IEEE}
}`,
'vldb20-slowsql': `@article{ma2020diagnosing,
  title={Diagnosing root causes of intermittent slow queries in cloud databases},
  author={Ma, Minghua and Yin, Zheng and Zhang, Shenglin and Wang, Sheng and Zheng, Christopher and Jiang, Xinhao and Hu, Hanwen and Luo, Cheng and Li, Yilin and Qiu, Nengjun and others},
  journal={Proceedings of the VLDB Endowment},
  volume={13},
  number={8},
  pages={1176--1189},
  year={2020},
  publisher={VLDB Endowment}
}`,
'atc21-JumpStarter': `@inproceedings{ma2021jump,
  title={$\{$Jump-Starting$\}$ multivariate time series anomaly detection for online service systems},
  author={Ma, Minghua and Zhang, Shenglin and Chen, Junjie and Xu, Jim and Li, Haozhe and Lin, Yongliang and Nie, Xiaohui and Zhou, Bo and Wang, Yong and Pei, Dan},
  booktitle={USENIX Annual Technical Conference (USENIX ATC 21)},
  pages={413--426},
  year={2021}
}`,
'dexa22-FPG-Miner': `@inproceedings{li2022mining,
  title={Mining fluctuation propagation graph among time series with active learning},
  author={Li, Mingjie and Ma, Minghua and Nie, Xiaohui and Yin, Kanglin and Cao, Li and Wen, Xidao and Yuan, Zhiyun and Wu, Duogang and Li, Guoying and Liu, Wei and others},
  booktitle={International Conference on Database and Expert Systems Applications},
  pages={220--233},
  year={2022},
  organization={Springer}
}`,
'www22-parsing': `@inproceedings{liu2022uniparser,
  title={Uniparser: A unified log parser for heterogeneous log data},
  author={Liu, Yudong and Zhang, Xu and He, Shilin and Zhang, Hongyu and Li, Liqun and Kang, Yu and Xu, Yong and Ma, Minghua and Lin, Qingwei and Dang, Yingnong and others},
  booktitle={Proceedings of the ACM Web Conference 2022},
  pages={1893--1901},
  year={2022}
}`,
'kdd22-mthc': `@inproceedings{liu2022multi,
  title={Multi-task hierarchical classification for disk failure prediction in online service systems},
  author={Liu, Yudong and Yang, Hailan and Zhao, Pu and Ma, Minghua and Wen, Chengwu and Zhang, Hongyu and Luo, Chuan and Lin, Qingwei and Yi, Chang and Wang, Jiaojian and others},
  booktitle={Proceedings of the 28th ACM SIGKDD Conference on Knowledge Discovery and Data Mining},
  pages={3438--3446},
  year={2022}
}`,
'fse22-logsurvey': `@inproceedings{he2022empirical,
  title={An empirical study of log analysis at Microsoft},
  author={He, Shilin and Zhang, Xu and He, Pinjia and Xu, Yong and Li, Liqun and Kang, Yu and Ma, Minghua and Wei, Yining and Dang, Yingnong and Rajmohan, Saravanakumar and others},
  booktitle={Proceedings of the 30th ACM Joint European Software Engineering Conference and Symposium on the Foundations of Software Engineering},
  pages={1465--1476},
  year={2022}
}`,
'fse22-disk': `@inproceedings{ma2022empirical,
  title={An empirical investigation of missing data handling in cloud node failure prediction},
  author={Ma, Minghua and Liu, Yudong and Tong, Yuang and Li, Haozhe and Zhao, Pu and Xu, Yong and Zhang, Hongyu and He, Shilin and Wang, Lu and Dang, Yingnong and others},
  booktitle={Proceedings of the 30th ACM Joint European Software Engineering Conference and Symposium on the Foundations of Software Engineering},
  pages={1453--1464},
  year={2022}
}`,
'seip23-conan': `@inproceedings{li2023conan,
  title={Conan: Diagnosing batch failures for cloud systems},
  author={Li, Liqun and Zhang, Xu and He, Shilin and Kang, Yu and Zhang, Hongyu and Ma, Minghua and Dang, Yingnong and Xu, Zhangwei and Rajmohan, Saravan and Lin, Qingwei and others},
  booktitle={2023 IEEE/ACM 45th International Conference on Software Engineering: Software Engineering in Practice (ICSE-SEIP)},
  pages={138--149},
  year={2023},
  organization={IEEE}
}`,
'seip23-traceark': `@inproceedings{zeng2023traceark,
  title={Traceark: Towards actionable performance anomaly alerting for online service systems},
  author={Zeng, Zhengran and Zhang, Yuqun and Xu, Yong and Ma, Minghua and Qiao, Bo and Zou, Wentao and Chen, Qingjun and Zhang, Meng and Zhang, Xu and Zhang, Hongyu and others},
  booktitle={2023 IEEE/ACM 45th International Conference on Software Engineering: Software Engineering in Practice (ICSE-SEIP)},
  pages={258--269},
  year={2023},
  organization={IEEE}
}`,
'seip23-ageis': `@inproceedings{yan2023aegis,
  title={Aegis: Attribution of control plane change impact across layers and components for cloud systems},
  author={Yan, Xiaohan and Hsieh, Ken and Liyanage, Yasitha and Ma, Minghua and Chintalapati, Murali and Lin, Qingwei and Dang, Yingnong and Zhang, Dongmei},
  booktitle={2023 IEEE/ACM 45th International Conference on Software Engineering: Software Engineering in Practice (ICSE-SEIP)},
  pages={222--233},
  year={2023},
  organization={IEEE}
}`,
'www23-DFP': `@inproceedings{lin2023edits,
  title={Edits: An easy-to-difficult training strategy for cloud failure prediction},
  author={Lin, Qingwei and Li, Tianci and Zhao, Pu and Liu, Yudong and Ma, Minghua and Zheng, Lingling and Chintalapati, Murali and Liu, Bo and Wang, Paul and Zhang, Hongyu and others},
  booktitle={Companion Proceedings of the ACM Web Conference 2023},
  pages={371--375},
  year={2023}
}`,
'dsn23-workload': `@inproceedings{qin2023different,
  title={How different are the cloud workloads? characterizing large-scale private and public cloud workloads},
  author={Qin, Xiaoting and Ma, Minghua and Zhao, Yuheng and Zhang, Jue and Du, Chao and Liu, Yudong and Parayil, Anjaly and Bansal, Chetan and Rajmohan, Saravan and Goiri, {\'I}{\~n}igo and others},
  booktitle={53rd Annual IEEE/IFIP International Conference on Dependable Systems and Networks (DSN)},
  pages={522--530},
  year={2023},
  organization={IEEE}
}`,
'kdd23-AnoFusion': `@inproceedings{zhao2023robust,
  title={Robust multimodal failure detection for microservice systems},
  author={Zhao, Chenyu and Ma, Minghua and Zhong, Zhenyu and Zhang, Shenglin and Tan, Zhiyuan and Xiong, Xiao and Yu, LuLu and Feng, Jiayi and Sun, Yongqian and Zhang, Yuzhi and others},
  booktitle={Proceedings of the 29th ACM SIGKDD Conference on Knowledge Discovery and Data Mining},
  pages={5639--5649},
  year={2023}
}`,
'fse23-detection_better': `@inproceedings{ganatra2023detection,
  title={Detection is better than cure: A cloud incidents perspective},
  author={Ganatra, Vaibhav and Parayil, Anjaly and Ghosh, Supriyo and Kang, Yu and Ma, Minghua and Bansal, Chetan and Nath, Suman and Mace, Jonathan},
  booktitle={Proceedings of the 31st ACM Joint European Software Engineering Conference and Symposium on the Foundations of Software Engineering},
  pages={1891--1902},
  year={2023}
}`,
'fse23-TraceDiag': `@inproceedings{ding2023tracediag,
  title={TraceDiag: Adaptive, Interpretable, and Efficient Root Cause Analysis on Large-Scale Microservice Systems},
  author={Ding, Ruomeng and Zhang, Chaoyun and Wang, Lu and Xu, Yong and Ma, Minghua and Wu, Xiaomin and Zhang, Meng and Chen, Qingjun and Gao, Xin and Gao, Xuedong and others},
  booktitle={Proceedings of the 31st ACM Joint European Software Engineering Conference and Symposium on the Foundations of Software Engineering},
  pages={1762--1773},
  year={2023}
}`,
'fse23-Assess&Summarize': `@inproceedings{jin2023assess,
  title={Assess and summarize: Improve outage understanding with large language models},
  author={Jin, Pengxiang and Zhang, Shenglin and Ma, Minghua and Li, Haozhe and Kang, Yu and Li, Liqun and Liu, Yudong and Qiao, Bo and Zhang, Chaoyun and Zhao, Pu and others},
  booktitle={Proceedings of the 31st ACM Joint European Software Engineering Conference and Symposium on the Foundations of Software Engineering},
  pages={1657--1668},
  year={2023}
}`,
'issre23-CODEC': `@inproceedings{li2023codec,
  title={Codec: Cost-effective duration prediction system for deadline scheduling in the cloud},
  author={Li, Haozhe and Ma, Minghua and Liu, Yudong and Qin, Si and Qiao, Bo and Yao, Randolph and Chaturvedi, Harshwardhan and Tran, Tri and Chintalapati, Murali and Rajmohan, Saravan and others},
  booktitle={2023 IEEE 34th International Symposium on Software Reliability Engineering (ISSRE)},
  pages={298--308},
  year={2023},
  organization={IEEE}
}`,
'eurosys24-AutoRCA': `@inproceedings{chen2024automatic,
  title={Automatic root cause analysis via large language models for cloud incidents},
  author={Chen, Yinfang and Xie, Huaibing and Ma, Minghua and Kang, Yu and Gao, Xin and Shi, Liu and Cao, Yunjie and Gao, Xuedong and Fan, Hao and Wen, Ming and others},
  booktitle={Proceedings of the Nineteenth European Conference on Computer Systems},
  pages={674--688},
  year={2024}
}`,
'icse24-Xpert': `@inproceedings{jiang2024xpert,
  title={Xpert: Empowering incident management with query recommendations via large language models},
  author={Jiang, Yuxuan and Zhang, Chaoyun and He, Shilin and Yang, Zhihao and Ma, Minghua and Qin, Si and Kang, Yu and Dang, Yingnong and Rajmohan, Saravan and Lin, Qingwei and others},
  booktitle={Proceedings of the IEEE/ACM 46th International Conference on Software Engineering},
  pages={1--13},
  year={2024}
}`,
'vldb24-ImDiffusion': `@article{chen2023imdiffusion,
  title={Imdiffusion: Imputed diffusion models for multivariate time series anomaly detection},
  author={Chen, Yuhang and Zhang, Chaoyun and Ma, Minghua and Liu, Yudong and Ding, Ruomeng and Li, Bowen and He, Shilin and Rajmohan, Saravan and Lin, Qingwei and Zhang, Dongmei},
  journal={arXiv preprint arXiv:2307.00754},
  year={2023}
}`,
'www24-VAE': `@inproceedings{wang2024revisiting,
  title={Revisiting VAE for Unsupervised Time Series Anomaly Detection: A Frequency Perspective},
  author={Wang, Zexin and Pei, Changhua and Ma, Minghua and Wang, Xin and Li, Zhihan and Pei, Dan and Rajmohan, Saravan and Zhang, Dongmei and Lin, Qingwei and Zhang, Haiming and others},
  booktitle={Proceedings of the ACM on Web Conference 2024},
  pages={3096--3105},
  year={2024}
}`,
'fse24-AutoRCA': `@inproceedings{zhang2024automated,
  title={Automated root causing of cloud incidents using in-context learning with GPT-4},
  author={Zhang, Xuchao and Ghosh, Supriyo and Bansal, Chetan and Wang, Rujia and Ma, Minghua and Kang, Yu and Rajmohan, Saravan},
  booktitle={Companion Proceedings of the 32nd ACM International Conference on the Foundations of Software Engineering},
  pages={266--277},
  year={2024}
}`,
'fse24-monitorassistant': `@inproceedings{yu2024monitorassistant,
  title={MonitorAssistant: Simplifying Cloud Service Monitoring via Large Language Models},
  author={Yu, Zhaoyang and Ma, Minghua and Zhang, Chaoyun and Qin, Si and Kang, Yu and Bansal, Chetan and Rajmohan, Saravan and Dang, Yingnong and Pei, Changhua and Pei, Dan and others},
  booktitle={Companion Proceedings of the 32nd ACM International Conference on the Foundations of Software Engineering},
  pages={38--49},
  year={2024}
}`,
'tnsm19-period': `@article{zhao2019automatic,
  title={Automatic and generic periodicity adaptation for kpi anomaly detection},
  author={Zhao, Nengwen and Zhu, Jing and Wang, Yao and Ma, Minghua and Zhang, Wenchi and Liu, Dapeng and Zhang, Ming and Pei, Dan},
  journal={IEEE Transactions on Network and Service Management},
  volume={16},
  number={3},
  pages={1170--1183},
  year={2019},
  publisher={IEEE}
}`,
'tsc23-robust': `@article{zhang2023robust,
  title={Robust failure diagnosis of microservice system through multimodal data},
  author={Zhang, Shenglin and Jin, Pengxiang and Lin, Zihan and Sun, Yongqian and Zhang, Bicheng and Xia, Sibo and Li, Zhengdan and Zhong, Zhenyu and Ma, Minghua and Jin, Wa and others},
  journal={IEEE Transactions on Services Computing},
  volume={16},
  number={6},
  pages={3851--3864},
  year={2023},
  publisher={IEEE}
}`,
'arxiv-DockerMock': `@article{li2021dockermock,
  title={DockerMock: Pre-build detection of dockerfile faults through mocking instruction execution},
  author={Li, Mingjie and Bai, Xiaoying and Ma, Minghua and Pei, Dan},
  journal={arXiv preprint arXiv:2104.05490},
  year={2021}
}`,
'arxiv-benchmark_dataset': `@article{li2022constructing,
  title={Constructing large-scale real-world benchmark datasets for aiops},
  author={Li, Zeyan and Zhao, Nengwen and Zhang, Shenglin and Sun, Yongqian and Chen, Pengfei and Wen, Xidao and Ma, Minghua and Pei, Dan},
  journal={arXiv preprint arXiv:2208.03938},
  year={2022}
}`,
'arxiv-enhance_fairness': `@article{ma2022enhanced,
  title={Enhanced fairness testing via generating effective initial individual discriminatory instances},
  author={Ma, Minghua and Tian, Zhao and Hort, Max and Sarro, Federica and Zhang, Hongyu and Lin, Qingwei and Zhang, Dongmei},
  journal={arXiv preprint arXiv:2209.08321},
  year={2022}
}`,
'arxiv-time_series': `@article{zhong2023survey,
  title={A Survey of Time Series Anomaly Detection Methods in the AIOps Domain},
  author={Zhong, Zhenyu and Fan, Qiliang and Zhang, Jiacheng and Ma, Minghua and Zhang, Shenglin and Sun, Yongqian and Lin, Qingwei and Zhang, Yuzhi and Pei, Dan},
  journal={arXiv preprint arXiv:2308.00393},
  year={2023}
}`,
'arxiv-taskwear': `@article{qiao2023taskweaver,
  title={Taskweaver: A code-first agent framework},
  author={Qiao, Bo and Li, Liqun and Zhang, Xu and He, Shilin and Kang, Yu and Zhang, Chaoyun and Yang, Fangkai and Dong, Hang and Zhang, Jue and Wang, Lu and others},
  journal={arXiv preprint arXiv:2311.17541},
  year={2023}
}`,
'arxiv-ufo': `@article{zhang2024ufo,
  title={Ufo: A ui-focused agent for windows os interaction},
  author={Zhang, Chaoyun and Li, Liqun and He, Shilin and Zhang, Xu and Qiao, Bo and Qin, Si and Ma, Minghua and Kang, Yu and Lin, Qingwei and Rajmohan, Saravan and others},
  journal={arXiv preprint arXiv:2402.07939},
  year={2024}
}`,
'arxiv-allhands': `@article{zhang2024allhands,
  title={AllHands: Ask Me Anything on Large-scale Verbatim Feedback via Large Language Models},
  author={Zhang, Chaoyun and Ma, Zicheng and Wu, Yuhao and He, Shilin and Qin, Si and Ma, Minghua and Qin, Xiaoting and Kang, Yu and Liang, Yuyi and Gou, Xiaoyu and others},
  journal={arXiv preprint arXiv:2403.15157},
  year={2024}
}`,
'zhang2024end': `@article{zhang2024end,
  title={End-to-End AutoML for Unsupervised Log Anomaly Detection},
  author={Zhang, Shenglin and Ji, Yuhe and Luan, Jiaqi and Nie, Xiaohui and Chen, Zi’ang and Ma, Minghua and Sun, Yongqian and Pei, Dan},
  journal={Automated Software Engineering},
  year={2024}
}`,
'arxiv-aiopslab': `@article{chen2024aiopslab,
  title={AIOpsLab: A Holistic Framework to Evaluate AI Agents for Enabling Autonomous Clouds},
  author={Chen, Yinfang and Shetty, Manish and Somashekar, Gagan and Ma, Minghua and Simmhan, Yogesh and Mace, Jonathan and Bansal, Chetan and Wang, Rujia and Rajmohan, Saravan},
  year={2024},
  journal={Arxiv}
}`,
'arxiv-gui': `@article{zhang2024large,
  title={Large language model-brained gui agents: A survey},
  author={Zhang, Chaoyun and He, Shilin and Qian, Jiaxu and Li, Bowen and Li, Liqun and Qin, Si and Kang, Yu and Ma, Minghua and Lin, Qingwei and Rajmohan, Saravan and others},
  journal={arXiv preprint arXiv:2411.18279},
  year={2024}
}`,
'tosem-diagnosis': `@article{zhang2024failure,
  title={Failure diagnosis in microservice systems: A comprehensive survey and analysis},
  author={Zhang, Shenglin and Xia, Sibo and Fan, Wenzhao and Shi, Binpeng and Xiong, Xiao and Zhong, Zhenyu and Ma, Minghua and Sun, Yongqian and Pei, Dan},
  journal={ACM Transactions on Software Engineering and Methodology},
  year={2025}
}`,
'shetty2024building': `@inproceedings{shetty2024building,
  title={Building AI Agents for Autonomous Clouds: Challenges and Design Principles},
  author={Shetty, Manish and Chen, Yinfang and Somashekar, Gagan and Ma, Minghua and Simmhan, Yogesh and Zhang, Xuchao and Mace, Jonathan and Vandevoorde, Dax and Las-Casas, Pedro and Gupta, Shachee Mishra and others},
  booktitle={Proceedings of the 2024 ACM Symposium on Cloud Computing},
  pages={99--110},
  year={2024}
}`,
'zhang2024deoxys': `@inproceedings{zhang2024deoxys,
  title={Deoxys: A Causal Inference Engine for Unhealthy Node Mitigation in Large-scale Cloud Infrastructure},
  author={Zhang, Chaoyun and Yao, Randolph and Qin, Si and Li, Ze and Agrawal, Shekhar and Mishra, Binit R and Tran, Tri and Ma, Minghua and Lin, Qingwei and Chintalapati, Murali and others},
  booktitle={Proceedings of the 2024 ACM Symposium on Cloud Computing},
  pages={361--379},
  year={2024}
}`,
'zhang2024end': `@inproceedings{zhang2024end,
  title={End-to-end automl for unsupervised log anomaly detection},
  author={Zhang, Shenglin and Ji, Yuhe and Luan, Jiaqi and Nie, Xiaohui and Chen, Ziang and Ma, Minghua and Sun, Yongqian and Pei, Dan},
  booktitle={Proceedings of the 39th IEEE/ACM International Conference on Automated Software Engineering},
  pages={1680--1692},
  year={2024}
}`,
'tao2024giving': `@inproceedings{tao2024giving,
  title={Giving Every Modality a Voice in Microservice Failure Diagnosis via Multimodal Adaptive Optimization},
  author={Tao, Lei and Zhang, Shenglin and Jia, Zedong and Sun, Jinrui and Ma, Minghua and Li, Zhengdan and Sun, Yongqian and Yang, Canqun and Zhang, Yuzhi and Pei, Dan},
  booktitle={Proceedings of the 39th IEEE/ACM International Conference on Automated Software Engineering},
  pages={1107--1119},
  year={2024}
}`,  
'sun2024art': `@inproceedings{sun2024art,
  title={ART: A Unified Unsupervised Framework for Incident Management in Microservice Systems},
  author={Sun, Yongqian and Shi, Binpeng and Mao, Mingyu and Ma, Minghua and Xia, Sibo and Zhang, Shenglin and Pei, Dan},
  booktitle={Proceedings of the 39th IEEE/ACM International Conference on Automated Software Engineering},
  pages={1183--1194},
  year={2024}
}`, 
'zhang2024enhanced': `@inproceedings{zhang2024enhanced,
  title={Enhanced Fine-Tuning of Lightweight Domain-Specific Q\&A Model Based on Large Language Models},
  author={Zhang, Shenglin and Zhu, Pengtian and Ma, Minghua and Wang, Jiagang and Sun, Yongqian and Li, Dongwen and Wang, Jingyu and Guo, Qianying and Hua, Xiaolei and Zhu, Lin and others},
  booktitle={2024 IEEE 35th International Symposium on Software Reliability Engineering Workshops (ISSREW)},
  pages={61--66},
  year={2024},
  organization={IEEE}
}`, 
'liu2024early': `@inproceedings{liu2024early,
  title={Early Bird: Ensuring Reliability of Cloud Systems Through Early Failure Prediction},
  author={Liu, Yudong and Ma, Minghua and Zhao, Pu and Li, Tianci and Qiao, Bo and Li, Shuo and Li, Ze and Chintalapati, Murali and Dang, Yingnong and Bansal, Chetan and others},
  booktitle={2024 IEEE 35th International Symposium on Software Reliability Engineering Workshops (ISSREW)},
  pages={49--54},
  year={2024},
  organization={IEEE}
}`,
'wang2024large': `@inproceedings{wang2024large,
  title={Large Language Models Can Provide Accurate and Interpretable Incident Triage},
  author={Wang, Zexin and Li, Jianhui and Ma, Minghua and Li, Ze and Kang, Yu and Zhang, Chaoyun and Bansal, Chetan and Chintalapati, Murali and Rajmohan, Saravan and Lin, Qingwei and others},
  booktitle={2024 IEEE 35th International Symposium on Software Reliability Engineering (ISSRE)},
  pages={523--534},
  year={2024},
  organization={IEEE}
}`,
'li2024can': `@inproceedings{li2024can,
  title={Can We Trust Auto-Mitigation? Improving Cloud Failure Prediction with Uncertain Positive Learning},
  author={Li, Haozhe and Ma, Minghua and Liu, Yudong and Zhao, Pu and Li, Shuo and Li, Ze and Chintalapati, Murali and Dang, Yingnong and Bansal, Chetan and Rajmohan, Saravan and others},
  booktitle={2024 IEEE 35th International Symposium on Software Reliability Engineering (ISSRE)},
  pages={499--510},
  year={2024},
  organization={IEEE}
}`,
'yu2024pre': `@inproceedings{yu2024pre,
  title={Pre-trained kpi anomaly detection model through disentangled transformer},
  author={Yu, Zhaoyang and Pei, Changhua and Wang, Xin and Ma, Minghua and Bansal, Chetan and Rajmohan, Saravan and Lin, Qingwei and Zhang, Dongmei and Wen, Xidao and Li, Jianhui and others},
  booktitle={Proceedings of the 30th ACM SIGKDD Conference on Knowledge Discovery and Data Mining},
  pages={6190--6201},
  year={2024}
}`,
'xie2024microservice': `@inproceedings{xie2024microservice,
  title={Microservice root cause analysis with limited observability through intervention recognition in the latent space},
  author={Xie, Zhe and Zhang, Shenglin and Geng, Yitong and Zhang, Yao and Ma, Minghua and Nie, Xiaohui and Yao, Zhenhe and Xu, Longlong and Sun, Yongqian and Li, Wentao and others},
  booktitle={Proceedings of the 30th ACM SIGKDD Conference on Knowledge Discovery and Data Mining},
  pages={6049--6060},
  year={2024}
}`,
'ding2023everything': `@article{ding2023everything,
  title={Everything of thoughts: Defying the law of penrose triangle for thought generation},
  author={Ding, Ruomeng and Zhang, Chaoyun and Wang, Lu and Xu, Yong and Ma, Minghua and Zhang, Wei and Qin, Si and Rajmohan, Saravan and Lin, Qingwei and Zhang, Dongmei},
  journal={arXiv preprint arXiv:2311.04254},
  year={2023}
}`,
'zhao2025triage': `@Article{zhao2025triage,
 author = {Yongxin Zhao and Shenglin Zhang and Yujia Wu and Yuxin Sun and Yongqian Sun and Dan Pei and Chetan Bansal and Minghua Ma},
 booktitle = {arXiv.org},
 journal = {ArXiv},
 title = {Triage in Software Engineering: A Systematic Review of Research and Practice},
 volume = {abs/2511.08607},
 year = {2025}
}`,
'feng2025cooks': `@Article{feng2025cooks,
 author = {Shenglin Zhang and Xiaoyu Feng and Runzhou Wang and Minghua Ma and Wenwei Gu and Yongqian Sun and Zedong Jia and Jinrui Sun and Dan Pei},
 booktitle = {IEEE International Symposium on Software Reliability Engineering},
 journal = {2025 IEEE 36th International Symposium on Software Reliability Engineering (ISSRE)},
 pages = {1-12},
 title = {Too Many Cooks: Assessing the Need for Multi-Source Data in Microservice Failure Diagnosis},
 year = {2025}
}`
};
return bibtexData
}
